config/routes.rb
Rails.application.routes.draw do
  post 'add/user', to: 'rooms#add_user', as: :add_user
  resources :rooms do
    resources :messages
  end
  devise_for :users

  root "rooms#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_create_commit :broadcast_room_message_create
  after_update_commit :broadcast_room_message_update
  after_destroy_commit :broadcast_room_message_destroy

  private

  def broadcast_room_message_create
    broadcast_append_to(
      'room_messages_channel',
      partial: 'messages/message',
      locals: { message: self },
      target: "room_messages_div"
    )
  end

  def broadcast_room_message_update
    broadcast_replace_to(
      'room_messages_channel',
      partial: 'messages/message',
      locals: { message: self },
      target: "message_#{id}"
    )
  end

  def broadcast_room_message_destroy
    broadcast_remove_to(
      'room_messages_channel',
      target: "message_#{id}"
    )
  end
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true

  has_many :user_rooms
  has_many :users, through: :user_rooms
  has_many :messages

  after_update_commit :update_room_details

  private

  def update_room_details
    broadcast_replace_to(
      'rooms_details_mobile_channel',
      partial: 'shared/room',
      locals: { room: self },
      target: "room_#{id}_mobile"
    )

    broadcast_replace_to(
      'rooms_details_desktop_channel',
      partial: 'shared/room',
      locals: { room: self },
      target: "room_#{id}_desktop"
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_rooms
  has_many :rooms, through: :user_rooms
  has_many :messages
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_commit on: :create do
    broadcast_append_to(
      'user_rooms_mobile_channel',
      partial: 'shared/room',
      locals: { room: Room.find(room_id) },
      target: "user_#{user_id}_rooms_mobile"
    )
  end
  after_commit on: :create do
    broadcast_append_to(
      'user_rooms_desktop_channel',
      partial: 'shared/room',
      locals: { room: Room.find(room_id) },
      target: "user_#{user_id}_rooms"
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_room, only: %i[create edit]
  before_action :set_message, only: %i[edit update destroy]

  def create
    @message = @room.messages.new message_params
    @message.user = current_user

    respond_to do |format|
      if @message.save
        format.turbo_stream
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @message.update message_params
        format.turbo_stream
      end
    end
  end

  def destroy
    @message.destroy

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def set_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:message)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @user = current_user.id
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        UserRoom.create(room: @room, user: current_user)
        format.turbo_stream { render turbo_stream: turbo_stream.append("rooms", partial: 'shared/room', locals: { room: @room })}
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace('room_form', partial: 'rooms/form', locals: { room: @room }) }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace("room_#{@room.id}", partial: 'shared/room', locals: { room: @room }) }
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy!

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_user
    UserRoom.create(room_id: params[:room_id], user_id: params[:user_id])

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.replace("room_show_#{params[:room_id]}", partial: 'rooms/room', locals: { room: Room.find(params[:room_id]) }) }
    end
  end

  def create_room
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.replace('room_form', partial: 'room/index') }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-screen bg-stone-800 ">
<head>
  <title>Fireside Chats</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0">
  <meta name="turbo:authenticated" content="<%= user_signed_in? %>">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= favicon_link_tag 'favicon.svg' %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <style>
    <%= "#msg_#{current_user&.id}" %> {
      background-color: rgb(234 88 12);
    }

    <%= "#cont_#{current_user&.id}" %> {
      display: flex;
      justify-content: flex-end;
    }
  </style>
</head>

<body>
<main class="w-full mt-10 md:m-0">
  <%= yield %>
</main>
</body>
</html>

app/views/messages/_form.html.erb
<div class="w-full" data-controller="form">
  <%= form_with(model: [room, message], id: 'message_form', class: 'w-full flex flex-col', data: { controller: 'form', action: 'submit->form#resetComponent' }) do |f| %>
    <div class="flex w-full">
      <%= f.text_field :message, class: 'w-full rounded-l-lg shadow text-sm font-semibold border border-gray-100' %>
      <%= f.button type: 'submit', class: 'bg-orange-600 font-semibold rounded-r-lg p-2' do %>
        <%= image_tag('send.svg', width: 25) %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/messages/_message.html.erb
<%= turbo_frame_tag "message_#{message.id}", class: "w-full" do %>
  <div id="<%= "cont_#{message.user.id}" %>" class="w-full">
    <div id="<%= "msg_#{message.user.id}" %>" class="flex justify-between items-center w-2/3 bg-gray-100 rounded-lg mb-2">
      <div class="p-3 ml-3 flex flex-col gap-1">
        <span class="text-gray-600 text-sm font-semibold"><%= message.user.email %></span>
        <span class="text-gray-800 text-xs"><%= message.message %></span>
        <span class="text-gray-800 text-xs font-semibold"><%= message.created_at.strftime('%b %e, %Y %l:%M %p') %></span>
      </div>

      <div data-controller="dropdown" data-action="click->dropdown#toggle click@window->dropdown#hide">
        <div id="dropdown-button" class="relative inline-block">
          <div role="button" tabindex="0" data-dropdown-target="button" class="inline-block select-none">
      <span class="appearance-none flex items-center inline-block">
        <%= image_tag('ellipsis-vertical.svg', width: 25, class: 'm-4') %>
      </span>
          </div>
          <div data-dropdown-target="menu"
               data-transition-enter="transition ease-out duration-200"
               data-transition-enter-from="opacity-0 translate-y-1"
               data-transition-enter-to="opacity-100 translate-y-0"
               data-transition-leave="transition ease-in duration-150"
               data-transition-leave-from="opacity-100 translate-y-0"
               data-transition-leave-to="opacity-0 translate-y-1"
               class="hidden absolute top-4 right-0 z-10 mt-5 flex w-screen max-w-max">
            <div class="text-sm bg-white shadow-lg rounded border overflow-hidden w-32">
              <%= link_to edit_room_message_path(message, room_id: message.room), class: 'no-underline block pl-4 py-2 text-gray-900 bg-white hover:bg-gray-100 whitespace-no-wrap' do %>
                Edit
              <% end %>
              <%= button_to room_message_path(message.room, message), class: 'no-underline w-full text-left block pl-4 py-2 text-gray-900 bg-white hover:bg-gray-100 whitespace-no-wrap', method: :delete do %>
                Delete
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/messages/edit.html.erb
<%= turbo_frame_tag "message_#{@message.id}", class: 'bg-gray-200 w-full px-3 py-2 flex justify-between rounded items-center gap-2 shadow' do %>
  <%= render 'messages/form', { room: @room, message: @message } %>
<% end %>

app/views/rooms/_form.html.erb
<%= form_with(model: room, class: "flex flex-col my-3 w-full") do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-col gap-1 justify-center">
    <%= form.label :name, class: 'text-white font-semibold text-sm' %>
    <%= form.text_field :name, class: 'w-full rounded border border-gray-200 font-semibold text-xs' %>
  </div>

  <div class="flex mt-2 gap-2 justify-end">
    <%= form.submit class: "cursor-pointer p-2 text-sm text-white font-semibold bg-orange-600 rounded" %>
    <%#= link_to 'Cancel', :back, class: 'cursor-pointer p-2 text-sm text-orange-600 font-semibold bg-white rounded' %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<section class="flex flex-col gap-2 mt-10 items-center justify-center w-full" id="room_show_<%= "#{room.id}" %>">
  <div class="flex flex-col">
    <h3 class="font-bold text-4xl text-white"><%= room.name %> - Room</h3>
  </div>

  <section class="flex gap-5">
    <div class="py-2 px-10 flex flex-col gap-1 items-center border-2 border-orange-600 rounded-lg my-2 shadow-lg w-fit">
      <h3 class="font-bold text-2xl text-white">Users in this room:</h3>
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 text-center">
        <% User.all.each do |user| %>
          <%= next unless room.users.include?(user) %>
          <div class="self-center text-white my-1 font-semibold text-sm">
            <%= user.email %>
          </div>
        <% end %>
      </div>
    </div>
  </section>

</section>

app/views/rooms/edit.html.erb
<%= turbo_frame_tag "room_#{@room.id}_mobile" do %>
    <h4 class="font-medium text-center text-base text-white">Edit Room</h4>
  <%= render "form", room: @room %>
<% end %>

<%= turbo_frame_tag "room_#{@room.id}_desktop" do %>
  <h4 class="font-medium text-center text-base text-white">Edit Room</h4>
  <%= render "form", room: @room %>
<% end %>

app/views/rooms/index.html.erb
<%= turbo_frame_tag 'rooms_controller' do %>
  <div class="flex w-full h-screen">
    <%= render 'shared/navigation' %>
    <main class="flex w-full h-screen">
      <section class="flex flex-col items-center justify-center gap-5 h-screen w-full">
        <div class="bg-orange-600 rounded">
          <%= image_tag('fire.svg', width: 100, class: 'm-4') %>
        </div>
        <h1 class="text-4xl font-bold text-white">Fireside Chat App - Ruby on Rails 7</h1>
        <p class="text-white">This is a chat app with RoR</p>
      </section>
    </main>
  </div>
<% end %>

app/views/rooms/new.html.erb
<%= turbo_frame_tag 'room_form' do %>
  <h4 class="font-medium text-center text-base text-white">Create New Room</h4>
  <%= render "form", room: @room %>
<% end %>

app/views/rooms/shared/_side_bar.html.erb
<nav class="w-60 flex flex-col items-center justify-between border-2 border-blue-600">
  <%= render 'rooms/shared/create_room' %>
</nav>

app/views/rooms/show.html.erb
<%= turbo_frame_tag 'rooms_controller' do %>
<%= turbo_stream_from 'room_messages_channel' %>
  <div class="flex w-full h-screen">
    <%= render 'shared/navigation' %>
    <main class="flex flex-col w-full h-screen" data-controller="slideover" data-action="keydown.esc->modal#close">
      <section class="w-full flex flex-col gap-5 h-screen px-5">
        <%= render 'room', room: @room %>

        <div class="flex flex-col h-1/2 md:h-4/6 items-center w-full">
          <div class="flex flex-col h-full w-full items-center justify-center">
            <div data-controller="chat-scroll" class="h-full w-full bg-stone-600 rounded p-2 my-5 overflow-y-auto flex flex-col" id="room_messages_div" >
              <% @room.messages.order(:id).each do |message| %>
                <%= render 'messages/message', message: message%>
              <% end %>
            </div>
            <div class="flex flex-col w-5/6 items-center justify-center">
              <%= render 'messages/form', { room: @room, message: Message.new } %>
            </div>
          </div>


        </div>
      </section>

      <!-- begin sidebar/slideover -->
      <div id="sidebar-mobile">
        <div data-slideover-target="overlay"
             class="hidden fixed inset-0 flex z-40"
             data-transition-enter="transition ease-out duration-200"
             data-transition-enter-from="opacity-0"
             data-transition-enter-to="opacity-100"
             data-transition-leave="transition ease-in duration-150"
             data-transition-leave-from="opacity-100"
             data-transition-leave-to="opacity-0"
        >
          <div class="fixed inset-0">
            <div class="absolute inset-0 bg-gray-600 opacity-75"></div>
          </div>
          <div data-slideover-target="menu"
               class="hidden relative flex-1 flex flex-col max-w-xs w-full pt-5 pb-4 bg-gray-800"
               data-transition-enter="transition ease-out duration-200"
               data-transition-enter-from="opacity-0 -translate-x-full"
               data-transition-enter-to="opacity-100 translate-x-0"
               data-transition-leave="transition ease-in duration-150"
               data-transition-leave-from="opacity-100 translate-x-0"
               data-transition-leave-to="opacity-0 -translate-x-full"
          >
            <div class="absolute top-0 right-0 -mr-14 p-1">
              <button data-action="slideover#toggle" class="flex items-center justify-center h-12 w-12 rounded-full focus:outline-none focus:bg-gray-600" aria-label="Close sidebar">
                <svg class="h-6 w-6 text-white" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
                </svg>
              </button>
            </div>
            <div class="flex-shrink-0 flex items-center px-4">
              <h1 class="text-white text-2xl font-bold">Add New Users</h1>
            </div>
            <div class="mt-5 flex-1 h-0 overflow-y-auto">
              <nav class="px-2 space-y-1">
                <section class="flex gap-5">
                  <div class="flex flex-col gap-1 items-center w-96">
                    <% User.all.each do |user| %>
                      <%= next if @room.users.include?(user) %>
                      <%= button_to add_user_path, data: { action: "click->slideover#toggle" }, params: { user_id: user, room_id: @room }, id: "add_user#{user.id}", method: :post do %>
                        <div class="cursor-pointer hover:bg-orange-600 rounded py-2 px-10 border-2 w-full items-center text-center border-orange-600 text-white my-1 font-semibold text-sm">
                          <%= user.email %>
                        </div>
                      <% end %>
                    <% end %>
                  </div>
                </section>
              </nav>
            </div>
          </div>
          <div class="flex-shrink-0 w-14">
            <!-- Dummy element to force sidebar to shrink to fit close icon -->
          </div>
        </div>
      </div>
      <!-- end sidebar/slideover -->
      <button data-action="click->slideover#toggle click@window->slideover#hide" class="absolute z-10 right-0 bottom-0 bg-orange-600 text-white mr-4 mb-4 rounded-full shadow-md hover:bg-orange-700">
        <%= image_tag('plus.svg', width: 40, class: 'm-4') %>
      </button>
    </main>
  </div>
<% end %>

app/views/shared/_create_room.html.erb
<%= turbo_frame_tag 'room_form' do %>
  <section class="flex flex-col items-center justify-center gap-2 mb-5">
    <h3 class="text-white font-semibold text-sm text-center">Want to start a new conversation</h3>
    <%= link_to new_room_path, id: 'new-room', class: 'rounded-lg py-3 px-5 bg-orange-600 text-white font-semibold block text-center text-sm' do %>
    Create new room
    <% end %>
  </section>
<% end %>

app/views/shared/_mobile_nav.html.erb
<%= turbo_stream_from 'user_rooms_mobile_channel' %>
<%= turbo_stream_from 'rooms_details_mobile_channel' %>
<nav class="w-full md:w-60 flex flex-col h-fit md:h-screen items-center justify-between md:border-r-2 md:border-stone-950">
  <div class="mb-10 w-full md:m-0" data-view-type="<%= 'mobile' %>">
    <%= render 'shared/user_rooms_mobile' %>
  </div>
  <%= render 'shared/create_room' %>
</nav>

app/views/shared/_navigation.html.erb
<%= turbo_stream_from 'rooms_details_channel' %>
<header data-controller="header" class="fixed w-full bg-orange-600 top-0 md:hidden">
  <div class="relative flex flex-col w-full text-left lg:hidden">
    <div class="flex justify-between w-full">
      <%= image_tag('fire.svg', width: 30, class: 'ml-4') %>
      <%# Hamburger button %>
      <div>
        <button data-action="header#toggle" type="button" class="inline-flex justify-center  w-full px-4 py-2"
                id="options-menu" aria-haspopup="true" aria-expanded="true">
          <%= image_tag('hamburger.svg', width: 20, class: 'm-4') %>
        </button>
      </div>
    </div>

    <%# Dropdown menu with a default hidden class %>
    <div data-header-target="toggleable" class="hidden relative flex flex-col w-full pt-5 pb-4 bg-gray-800"
         data-transition-enter="transition ease-out duration-200"
         data-transition-enter-from="opacity-0 -translate-x-full"
         data-transition-enter-to="opacity-100 translate-x-0"
         data-transition-leave="transition ease-in duration-150"
         data-transition-leave-from="opacity-100 translate-x-0"
         data-transition-leave-to="opacity-0 -translate-x-full">
      <div class="py-1" role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
        <%= render 'shared/mobile_nav' %>
      </div>
    </div>
  </div>
</header>
<aside class="h-screen hidden md:block">
  <div>
    <%= render 'shared/side_bar' %>
  </div>
</aside>

app/views/shared/_room.html.erb
<%= turbo_frame_tag "room_#{room.id}", data: { id: room.id, controller: 'room' } do %>
  <div class="flex bg-stone-700 rounded p-2 group items-center border-stone-950 border-2 justify-between text-white font-semibold hover:shadow-lg hover:bg-stone-700 overflow-visible">
    <%= link_to room_path(room), class: 'font-semibold py-2 text-white text-sm', data: { turbo_frame: 'rooms_controller', action: 'click->header#toggle' } do %>
      <%= room.name %>
    <% end %>

    <%= link_to edit_room_path(room), class: 'block md:hidden group-hover:block relative' do %>
      <div class="bg-orange-600 rounded p-2">
        <%= image_tag('edit.svg', width: 20, class: 'font-semibold') %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_side_bar.html.erb
<%= turbo_stream_from 'user_rooms_desktop_channel' %>
<%= turbo_stream_from 'rooms_details_desktop_channel' %>
<nav class="w-full md:w-60 flex flex-col h-fit md:h-screen items-center justify-between md:border-r-2 md:border-stone-950">
  <div class="mb-10 w-full md:m-0" data-view-type="<%= 'desktop' %>">
    <%= render 'shared/user_rooms' %>
  </div>
  <%= render 'shared/create_room' %>
</nav>

app/views/shared/_user_rooms.html.erb
<section class="flex flex-col w-full">
  <!-- User Information and Logout -->
  <span class="text-white text-center font-semibold mt-5"><%= current_user.email %></span>
  <div class="flex items-center justify-center mt-2">
    <%= button_to 'Log out', destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'px-3 py-1 text-white bg-red-700 rounded font-semibold text-sm' %>
  </div>

  <!-- User Rooms -->
  <h3 class="text-white font-bold text-xl mt-3 text-center mb-2">My rooms</h3>
  <div class="flex flex-col px-3 gap-2 w-full" id="user_<%= current_user.id %>_rooms">
    <% current_user.rooms.all.each do |room| %>
      <%= render 'shared/room', { room: room } %>
    <% end %>
  </div>
</section>

app/views/shared/_user_rooms_mobile.html.erb
<section class="flex flex-col w-full">
  <!-- User Information and Logout -->
  <span class="text-white text-center font-semibold mt-5"><%= current_user.email %></span>
  <div class="flex items-center justify-center mt-2">
    <%= button_to 'Log out', destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'px-3 py-1 text-white bg-red-700 rounded font-semibold text-sm'%>
  </div>

  <!-- User Rooms -->
  <h3 class="text-white font-bold text-xl mt-3 text-center mb-2">My rooms</h3>
  <div class="flex flex-col px-3 gap-2 w-full" id="user_<%= current_user.id %>_rooms_mobile">
    <% current_user.rooms.all.each do |room| %>
      <%= render 'shared/room', { room: room } %>
    <% end %>
  </div>
</section>